In [27]:
import numpy as np
import pandas as pd

array = [[3.,4.,12.],
[45.,27.,33.]]



arr2D = np.random.randint(1,100,30).reshape((3,10))
# print (arr2D)
second = np.random.randint(1,100,40).reshape((4,10))
# print (second)
finalArr = arr2D,second
print (finalArr)
finalArr2=finalArr[0][2]
secondcolumn= finalArr[1][2]
print(finalArr2)
print(secondcolumn)
pf = pd.DataFrame(arr2D[2], index=second[2])
print(pf)
arr2D[0][9] = 7
arr2D[1][9] = 7
arr2D[2][9] = 7
second[0][9] = 7
second[1][9] = 7
second[2][9] = 7
second[3][9] = 7
print(arr2D)
print(second)

arr2D[2]=arr2D[0]+arr2D[1]
print (arr2D)
second[3]= second[0]+second[1]+second[2]
print (second)



(array([[25, 28, 53, 67, 59,  5, 51, 47, 14, 28],
       [69, 52,  1, 24, 17, 64, 74, 83, 57, 58],
       [73, 39, 80, 50, 80, 74, 16, 21, 90, 33]]), array([[51, 19, 38,  1, 81, 44, 23, 89, 62, 62],
       [19, 41, 59, 55, 17, 20, 55, 59, 76, 97],
       [63,  6, 15, 13, 32, 71, 74, 25, 23, 24],
       [19, 33, 65, 98, 98, 19,  7, 59, 61, 87]]))
[73 39 80 50 80 74 16 21 90 33]
[63  6 15 13 32 71 74 25 23 24]
     0
63  73
6   39
15  80
13  50
32  80
71  74
74  16
25  21
23  90
24  33
[[25 28 53 67 59  5 51 47 14  7]
 [69 52  1 24 17 64 74 83 57  7]
 [73 39 80 50 80 74 16 21 90  7]]
[[51 19 38  1 81 44 23 89 62  7]
 [19 41 59 55 17 20 55 59 76  7]
 [63  6 15 13 32 71 74 25 23  7]
 [19 33 65 98 98 19  7 59 61  7]]
[[ 25  28  53  67  59   5  51  47  14   7]
 [ 69  52   1  24  17  64  74  83  57   7]
 [ 94  80  54  91  76  69 125 130  71  14]]
[[ 51  19  38   1  81  44  23  89  62   7]
 [ 19  41  59  55  17  20  55  59  76   7]
 [ 63   6  15  13  32  71  74  25  23   7]
 [133  66 112  69 1