In [17]:
import numpy as np

p= np.tile(8,(8,8))
print (p)
matrix = np.random.random((5,5))
print(matrix)
minima = np.min(matrix)
maxima = np.max(matrix)
div = maxima/minima
print (div)
arr = np.array([2,65,32,23], dtype=np.int16)
print (arr )
#  Create an array of 2x4 with dtype numpy.int16, print the dtype of the array (RGBA)
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)
# 26.
# first print = [1,2,3,4]
# second print = error

# 27. Z**Z = legal
# Z <- Z = illegal statement
#  = legal
# 28.

# np.array(0) / np.array(0) = 0
# np.array(0) // np.array(0) error

def round_array(x,y):
    return np.round(x,y)

test = np.array([32.11, 51.5, 0.112])
print(round_array(test,0))

res2= np.array([1,5,8,34,65])
res3 = np.array([ 5,8,45,65,3])
res4 = np.intersect1d(res2,res3)
print(res4)

[[8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]]
[[0.27738029 0.06127068 0.91319405 0.05157337 0.50252037]
 [0.10958951 0.69089464 0.6879904  0.66527936 0.9223167 ]
 [0.80505127 0.83367615 0.46318172 0.22793225 0.33241102]
 [0.02684769 0.94351672 0.96137117 0.40177232 0.11178022]
 [0.46481613 0.47932404 0.81987581 0.48678858 0.87737667]]
35.808341744578954
[ 2 65 32 23]
First array:
[[0.49456122 0.96743464 0.07258826]
 [0.55912805 0.32740212 0.54648172]
 [0.70301708 0.38813653 0.02890801]
 [0.66519553 0.48994321 0.05765831]
 [0.88619059 0.39828435 0.24604462]]
Second array:
[[0.52227656 0.8708689 ]
 [0.76498207 0.94643551]
 [0.80958527 0.92278625]]
Dot product of two arrays:
[[1.05713427 1.41329592]
 [0.98489977 1.30107804]
 [0.68749033 1.00625782]
 [0.76889312 1.09620405]
 [0.96671106 1.37575287]]
[32. 52.  0.]
[ 5  8 65]
